---
- name: Vault secret-change against vault.nostromo.io
  hosts: all
  sources:
    - hashicorp.vault.vault_audit:
        ssh_host: vault.nostromo.io
        ssh_user: root
        audit_path: /opt/vault/logs/audit.json

  rules:
    - name: Rotate app and database passwords
      condition: >-
        event.vault.path is match("secret/(data|delete)/eda-demo/.*")
        and (event.vault.operation == "update"
             or event.vault.operation == "create"
             or event.vault.operation == "delete")
      action:
        run_job_template:
          name: Vault rotate app and db passwords
          organization: Default
          job_args:
            extra_vars:
              secret_path: "{{ event.vault.path }}"
              operation: "{{ event.vault.operation }}"
              event_time: "{{ event.audit.time }}"
